require('mappings')
require('settings')
require('lazyinstall')
require('lazy').setup('plugins')
-- require('lazy').setup('plugins.lang')
require('colorschemes')
-- require('mini_init')
require('autocmd')
require('filetypes')
