---

- name: "install kitty terminal"
  hosts: localhost
  connection: local
  tasks:

  - name: create temporary dir for installation script
    tempfile:
      state: directory
      suffix: kitty_dotfile
    register: kitty_dotfile_tmp

  - name: download kitty installation script
    get_url:
      url: https://sw.kovidgoyal.net/kitty/installer.sh
      dest: "{{ kitty_dotfile_tmp.path }}"
      mode: 0755

  - name: execute installation script
    command:
      cmd: sh {{ kitty_dotfile_tmp.path  }}/installer.sh
      creates: ~/.local/kitty.app

  - name: create symlink to .local/bin
    file:
      src: "~/.local/kitty.app/bin/{{ item }}" 
      dest: "~/.local/bin/{{ item }}"
      state: link
    loop:
    - kitty
    - kitten
