---

- name: "install ricing tools"
  hosts: localhost
  connection: local
  tasks:

  - name: install ricing tools
    apt:
      pkg:
      - bspwm
      - polybar
      - rofi
      - lightdm
      - sxhkd
      - picom
      - dunst
      - feh
      - blueman
      - brightnessctl
      - pulsemixer
      - playerctl
      - cava
    become: true

  - name: install rofi-bluetooth
    git:
      repo: https://github.com/nickclyde/rofi-bluetooth.git
      dest: "{{ apps_directory }}/rofi-bluetooth"

  - name: link rofi-bluetooth in local/bin
    file:
      src: "{{ apps_directory }}/rofi-bluetooth/rofi-bluetooth"
      dest: ~/.local/bin/rofi-bluetooth
      state: link
