---

- name: "install funny stuffs"
  hosts: localhost
  connection: local
  tasks:

  - name: install unimatrix
    get_url:
      url: https://raw.githubusercontent.com/will8211/unimatrix/master/unimatrix.py
      dest: ~/Apps/unimatrix.py
      mode: 0755

  - name: install funny apps
    apt:
      pkg:
      - cool-retro-term
      - tty-clock
    become: true

  - name: install social networks
    snap:
      name:
      - discord
      - musikcube
    become: true

# TODO add gruvbox-factory
