---

- name: "setup base configuration"
  hosts: localhost
  connection: local
  tasks:

  - name: create ~/.local/bin directory
    file:
      state: directory
      path: ~/.local/bin

  - name: set ~/.local/bin in PATH
    blockinfile:
      path: ~/.bashrc
      block: |
        export PATH=$PATH:${HOME}/.local/bin
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
