---

- name: "Clone, make and install Neovim"
  hosts: localhost
  connection: local
  tasks:

  - name: install build dependencies
    apt:
      pkg:
      - libtool
      - libtool-bin
      - autoconf
      - automake
      - cmake
      - g++
      - pkg-config
      - ripgrep
    become: true

  - name: set directories variables
    set_fact:
      sources_directory: "{{ ansible_env.HOME }}/Apps/sources"
      install_directory: "{{ ansible_env.HOME }}/Apps/nvim"
      local_bin_directory: "{{ ansible_env.HOME }}/.local/bin"
      config_directory: "{{ ansible_env.HOME }}/.config"

  - name: create Neovim destination dir
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{ sources_directory }}"
      - "{{ local_bin_directory }}"

  - name: clone Neovim sources
    git:
      repo: https://github.com/neovim/neovim.git
      dest: "{{ sources_directory }}/neovim"
      version: stable
      update: yes
      force: yes

  - name: configure Neovim build
    shell:
      chdir: "{{ sources_directory }}/neovim"
      cmd: make CMAKE_BUILD_TYPE=Release -j 4

  - name: install Neovim
    shell:
      chdir: "{{ sources_directory }}/neovim"
      cmd: "make CMAKE_INSTALL_PREFIX={{ install_directory }} install"

  - name: create neovim symlink
    file:
      src: "{{ install_directory }}/bin/nvim"
      dest: "{{ local_bin_directory }}/nvim"
      state: link

  - name: install nvim config
    copy:
      src: "{{ playbook_dir }}/../.config/nvim"
      dest: "{{ config_directory }}"

  - name: create temp directory for NVM install
    tempfile:
      prefix: nvim_nvm_
      state: directory
    register: nvm_install_tmp

  - name: download install script nvm (for coc nvim plugin)
    get_url:
      url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
      dest: "{{ nvm_install_tmp.path }}/install.sh"
      mode: 0755

  - name: install nvm
    shell:
      executable: /bin/bash
      chdir: "{{ nvm_install_tmp.path }}"
      cmd: ./install.sh

  - name: set node version
    shell:
      executable: /bin/bash
      cmd: "source {{ ansible_env.HOME }}/.nvm/nvm.sh; nvm install 17.6.0"

