---

- name: "install kube tools"
  hosts: localhost
  connection: local
  vars:
    kube_tools_k9s_version: v0.32.4
  tasks:

  - name: set directories variables
    set_fact:
      local_bin_directory: "{{ ansible_env.HOME }}/.local/bin"
      home_user: "{{ ansible_env.HOME }}"
      bash_completions_directory: "{{ ansible_env.HOME }}/.local/share/bash-completion/completions"
    tags: always

  - name: create completions directory
    file:
      path: "{{ bash_completions_directory }}"
      state: directory
    tags: always

  - name: get kubectl stable release version
    uri:
      url: https://dl.k8s.io/release/stable.txt
      return_content: true
    register: stable_version
    failed_when: stable_version is failed
    tags: kubectl

  - name: get kubectl stable release checksum
    uri:
      url: "https://dl.k8s.io/release/{{ stable_version.content }}/bin/linux/amd64/kubectl.sha256"
      return_content: true
    register: kubectl_checksum
    failed_when: kubectl_checksum is failed
    tags: kubectl

  - name: download kubectl stable release
    get_url:
      url: "https://dl.k8s.io/release/{{ stable_version.content }}/bin/linux/amd64/kubectl"
      dest: "{{ local_bin_directory }}/kubectl"
      checksum: "sha256:{{ kubectl_checksum.content }}"
      mode: 0755
    tags: kubectl

  - name: clone kubectx (kubectl plugin)
    git:
      repo: https://github.com/ahmetb/kubectx.git
      dest: "{{ home_user }}/Apps/kubectx"
    tags: kubectx

  - name: link kubectx completion
    file:
      src: "{{ home_user }}/Apps/kubectx/completion/{{ item }}.bash"
      dest: "{{ bash_completions_directory }}/{{ item }}"
      state: link
      force: true
    loop:
    - kubens
    - kubectx
    tags: kubectx

  - name: link kubectx binaries to local bin
    file:
      src: "{{ home_user }}/Apps/kubectx/{{ item }}"
      dest: "{{ local_bin_directory }}/{{ item }}"
      state: link
      force: true
    loop:
    - kubens
    - kubectx
    tags: kubectx

  - name: install k9s
    apt:
      deb: https://github.com/derailed/k9s/releases/download/{{ kube_tools_k9s_version }}/k9s_linux_amd64.deb
    become: yes
    tags: k9s
