---

- name: "Clone, make and install Neovim"
  hosts: localhost
  connection: local
  tasks:

  - name: set directories variables
    set_fact:
      install_directory: "{{ ansible_env.HOME }}/Apps/nvim"
      local_bin_directory: "{{ ansible_env.HOME }}/.local/bin"
      config_directory: "{{ ansible_env.HOME }}/.config"

  - name: install package dependencies
    apt:
      pkg:
      - isort
      - black
      - yamllint
    become: true

  - name: create Neovim destination dir
    file:
      path: "{{ item }}"
      state: directory
    loop:
      - "{{ install_directory }}"
      - "{{ local_bin_directory }}"

  - name: download neovim nightly
    get_url:
      url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
      dest: "{{ install_directory }}"
      checksum: sha256:https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz.sha256sum

  - name: extract neovim archive
    unarchive:
      src: "{{ install_directory }}/nvim-linux64.tar.gz"
      dest: "{{ install_directory }}"

  - name: create neovim symlink
    file:
      src: "{{ install_directory }}/nvim-linux64/bin/nvim"
      dest: "{{ local_bin_directory }}/nvim"
      state: link

  - name: install nvim config
    copy:
      src: "{{ playbook_dir }}/../.config/nvim"
      dest: "{{ config_directory }}"

  - name: create temp directory for NVM install
    tempfile:
      prefix: nvim_nvm_
      state: directory
    register: nvm_install_tmp

  - name: download install script nvm (for coc nvim plugin)
    get_url:
      url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh
      dest: "{{ nvm_install_tmp.path }}/install.sh"
      mode: 0755

  - name: install nvm
    shell:
      executable: /bin/bash
      chdir: "{{ nvm_install_tmp.path }}"
      cmd: ./install.sh

  - name: set node version
    shell:
      executable: /bin/bash
      cmd: "source {{ ansible_env.HOME }}/.nvm/nvm.sh; nvm install 17.6.0"

  - name: install pip dependencies
    pip:
      executable: ~/.pyenv/versions/3.10.7/bin/pip3
      name:
      - isort
      - black
      - yamllint
      - neovim
      - tree-sitter
      extra_args: '--upgrade'

  - name: install getnf (get nerd font)
    git:
      repo: https://github.com/ronniedroid/getnf.git
      dest: ~/Apps/getnf

  - name: install getnf
    command:
      chdir: ~/Apps/getnf
      cmd: ./install.sh
      creates: ~/.local/bin/getnf

  - name: install merd fonts
    shell: echo 31 | getnf


