---

- name: "setup base configuration"
  hosts: localhost
  connection: local
  tasks:

  - name: set ~/.local/bin in PATH
    blockinfile:
      path: ~/.bashrc
      block: |
        export PATH=$PATH:${HOME}/.local/bin
        setxkbmap -option caps:swapescape
        setxkbmap -option compose:ralt
        ssh_agent_pid=$(ps -ef | grep -v grep | grep 'ssh-agent' | awk '{printf $2}')
        if [[ "${ssh_agent_pid}" == "" ]]; then
          eval $(ssh-agent) > /dev/null # to type only once the ssh passphrase
        fi
      marker: "# {mark} ANSIBLE MANAGED BLOCK"

  - name: add color_prompt in bashrc for kitty
    lineinfile:
      path: ~/.bashrc
      regexp: '^\s*xterm-color\|.*\).*color_prompt=yes;;'
      line: '    xterm-color|xterm-kitty|*-256color|screen) color_prompt=yes;;'

  - name: copy kitty config
    synchronize:
      src: "{{ playbook_dir }}/../.config/kitty"
      dest: ~/.config

  - name: copy ricing config
    synchronize:
      src: "{{ playbook_dir }}/../.config/{{ item }}"
      dest: ~/.config
    loop:
    - bspwm
    - picom
    - polybar
    - rofi
    - sxhkd
    - dunst
    - neofetch
    - MangoHud

  - name: copy gitconfig
    copy:
      src: "{{ playbook_dir }}/../.gitconfig"
      dest: ~/.gitconfig

  - name: copy share directory
    synchronize:
      src: "{{ playbook_dir }}/../share/{{ item }}"
      dest: ~/.local/share
    loop:
    - wallpapers

  - name: copy sshh config
    synchronize:
      src: "{{ playbook_dir }}/../ssh/config"
      dest: ~/.ssh/config

  # move in specific playbook
  - name: install rofi-wallpaper
    file:
      state: link
      src: ~/.config/rofi/scripts/wallpapers_selector.sh
      dest: ~/.local/bin/rofi-wallpaper
