---

- name: "install funny stuffs"
  hosts: localhost
  connection: local
  tasks:

  - name: install unimatrix
    get_url:
      url: https://raw.githubusercontent.com/will8211/unimatrix/master/unimatrix.py
      dest: ~/Apps/unimatrix.py
      mode: 0755

  - name: install funny apps
    apt:
      pkg:
      - cool-retro-term
      - tty-clock
    become: true

  - name: install social networks
    snap:
      name:
      - discord
    become: true

  - name: install musikcube
    apt:
      deb: https://github.com/clangen/musikcube/releases/download/3.0.2/musikcube_3.0.2_linux_x86_64.deb
    become: true
    tags: musikcube


# TODO add gruvbox-factory
